lightgbm_neural:
  model_type: lightgbm
  model_dir: /data/nzh/ylmodel_online/models/lightgbm_neural
  model_path: null
  label: 10min-totalcap-industry-1d-rank
  seq_len: 1
  hyper_parameter:
    objective: regression
    boosting_type: gbdt
    extra_trees: True
    metric: rmse
    learning_rate: 0.05
    min_child_samples: 120
    colsample_bytree: 0.7
    subsample: 0.85
    reg_alpha: 0.01
    reg_lambda: 0.01
    num_leaves: 96
    max_depth: 12
    drop_rate: 0.0
    n_estimators: 100
