tabnet_5d:
  model_type: tabnet
  model_dir: /data/nzh/ylmodel_online/models/tabnet_5d
  model_path: null
  label: ret_open_10min-5d-rank
  seq_len: 1
  hyper_parameter:
    n_d: 8
    n_a: 8
    n_steps: 3
    gamma: 1.3
    cat_emb_dim: 1
    n_independent: 2
    n_shared: 2
    epsilon: 1.0e-15
    momentum: 0.02
    lambda_sparse: 1.0e-3
    clip_value: 1
    verbose: 10
    mask_type: entmax
    device_name: cuda