tabnet_neural:
  model_type: tabnet
  model_dir: /data/nzh/ylmodel_online/models/tabnet_neural
  model_path: null
  label: 10min-totalcap-industry-1d-rank
  seq_len: 1
  hyper_parameter:
    n_d: 8
    n_a: 8
    n_steps: 3
    gamma: 1.3
    cat_emb_dim: 1
    n_independent: 2
    n_shared: 2
    epsilon: 1.0e-15
    momentum: 0.02
    lambda_sparse: 1.0e-3
    clip_value: 1
    verbose: 10
    mask_type: entmax
    device_name: cuda