defaults:
  - _self_
  - models:
    # TODO: 设置需要选用的基模型超参数文件，将基模型超参数文件放在config/models路径下 
    - lightgbm_1d
    - lightgbm_5d
    - lightgbm_10d
    - lightgbm_neural
    - xgboost_1d
    - xgboost_5d
    - xgboost_10d
    - xgboost_neural
    - tabnet_1d
    - tabnet_5d
    - tabnet_10d
    - tabnet_neural
    - tcn_1d
    - tcn_5d
    - tcn_10d
    - tcn_neural
  
hydra:
  run:
    dir: /data/nzh/ylmodel_online/logs/hydra/${now:%Y-%m-%d_%H_%M_%S}
  job_logging:
    formatters:
      simple:
        format: '%(asctime)s [%(levelname)s][%(name)s][%(module)s][%(funcName)s] %(message)s'

settings:
  dirs:
    working: ${hydra:runtime.cwd}

seed: 17440

ensemble_weights: [0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625, 0.0625]
